### ISSUE TITLE
Various websites are broken.

### ISSUE THREAD

**Issue by andrigamerita** [xAlcahest/AdKillerDNS#1]
Reporting various broken websites.

---
First, Microsoft.com. As can be seen in the screenshots, it seems like any page on microsoft.com loads, but is broken: images do not load.

![Screenshot_2021-01-18_17-53-24](https://user-images.githubusercontent.com/37557992/104943856-a8739880-59b6-11eb-863b-61cc1bcae0a5.png)
![Screenshot_2021-01-18_17-53-31](https://user-images.githubusercontent.com/37557992/104943858-a90c2f00-59b6-11eb-93ed-f5aead3eb70d.png)

---
Bing.com doesn't load at all. The browser tells there is a certificate issue.

![Screenshot_2021-01-18_17-52-42](https://user-images.githubusercontent.com/37557992/104943847-a6113e80-59b6-11eb-8924-5c888133d954.png)
![Screenshot_2021-01-18_17-52-58](https://user-images.githubusercontent.com/37557992/104943850-a7426b80-59b6-11eb-9ce2-9c47deb577da.png)

---
Every Yahoo.com page seems to load, but with a major problem that makes them very broken: the website CSS layout seems to not be loaded.

![Screenshot_2021-01-18_17-53-16](https://user-images.githubusercontent.com/37557992/104943855-a7db0200-59b6-11eb-924d-35cd357f1b56.png)
![Screenshot_2021-01-18_17-55-31](https://user-images.githubusercontent.com/37557992/104943861-a9a4c580-59b6-11eb-9849-6860260df139.png)

---
Every website issue has been verified to exist both on Firefox and Chromium.

**Comment by xAlcahest** [comment]
How is it now? Do you still see these errors and certificate errors?

**Comment by xAlcahest** [comment]
EDIT: We changed IP for AdKillerDNS: 194.15.36.210
